### ISSUE TITLE
width height reversed

### ISSUE THREAD

**Issue by pjbaron** [cojomojo/Shi_Tomasi_Feature_Detection#1]
Thank you for making this available, it is incredibly helpful!

While playing with the serial implementation I noticed a bug in line 211 of stfd.c
```   		eigenvalues[i].x >= image_height-1-ignore_x || eigenvalues[i].y >= image_width-1-ignore_y) {```

The x should use width and the y should use height, instead of vice-versa.

**Comment by balos1** [comment]
Thanks for reporting the issue. I have pushed up a fix in commit b73aa747e99f3bcb5a158859a065060753aad7c9. 

I am happy to hear someone found this useful!
